# Dask dataframe

![](https://avatars3.githubusercontent.com/u/17131925?s=400&v=4)

<font color = 'Orange' >Blog on Dask Dataframe ->[Visit Here](https://inblog.in/Data-manipulation-with-Dask-dataframe-kt6Z5irDVg)</font>

Code ref: [Data manipulation with Dask Dataframe](https://www.kaggle.com/code/aman2000jaiswal/data-manipulation-with-dask-dataframe/notebook)

**A Dask dataFrame is a large parallel dataFrame composed of many smaller Pandas DataFrames, split along the index. These Pandas DataFrames may live on disk for larger-than-memory computing on a single machine, or on many different machines in a cluster. One Dask dataFrame operation triggers many operations on the constituent Pandas DataFrames.**

Dask has its own set of data collections which extend the original collections like Pandas DataFrames & NumPy arrays.

Dask follows the lazy evaluation way where it forms a "graph" of the operation at hand, but doesn't process it until it is explicitly called for.

This complete parallel graph can also be viewed by calling the .visualize() method on it.

A 50gb Pandas DataFrame will be split by Dask into multiple DataFrames by row indices and then computed upon parallely.

The operation you need to perform becomes the "Task Graph" that Dask will perform on them parallely when the .compute() method is called.

Dask uses threads and processes to parallelise its computations on your local machine for data larger than your memory.

It is also compatible for scaling up to multiple machines by using schedulers to scale the same operation to 100s or even 1000s of clusters.ðŸš€

In [1]:
import warnings
warnings.filterwarnings(action="ignore")

In [2]:
import dask.dataframe as dd
import dask.array as da
import pandas as pd
import numpy as np

dask_df = dd.read_csv('/kaggle/input/us-accidents/US_Accidents_June20.csv')

In [3]:
# Checking dataframe partitions
dask_df.map_partitions(type).compute()

0     <class 'pandas.core.frame.DataFrame'>
1     <class 'pandas.core.frame.DataFrame'>
2     <class 'pandas.core.frame.DataFrame'>
3     <class 'pandas.core.frame.DataFrame'>
4     <class 'pandas.core.frame.DataFrame'>
5     <class 'pandas.core.frame.DataFrame'>
6     <class 'pandas.core.frame.DataFrame'>
7     <class 'pandas.core.frame.DataFrame'>
8     <class 'pandas.core.frame.DataFrame'>
9     <class 'pandas.core.frame.DataFrame'>
10    <class 'pandas.core.frame.DataFrame'>
11    <class 'pandas.core.frame.DataFrame'>
12    <class 'pandas.core.frame.DataFrame'>
13    <class 'pandas.core.frame.DataFrame'>
14    <class 'pandas.core.frame.DataFrame'>
15    <class 'pandas.core.frame.DataFrame'>
16    <class 'pandas.core.frame.DataFrame'>
17    <class 'pandas.core.frame.DataFrame'>
18    <class 'pandas.core.frame.DataFrame'>
19    <class 'pandas.core.frame.DataFrame'>
20    <class 'pandas.core.frame.DataFrame'>
dtype: object

In [4]:
# Checking length of each partition
dask_df.map_partitions(len).compute()

0     167822
1     168482
2     167261
3     166064
4     166092
5     166596
6     166406
7     167048
8     168116
9     168517
10    169023
11    169117
12    168194
13    168965
14    171139
15    175220
16    173411
17    173984
18    173713
19    171911
20    126536
dtype: int64

In [5]:
#Accessing one of the partition
dask_df.partitions[1].compute()

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-167824,MapQuest,201.0,2,2016-12-09 09:52:24,2016-12-09 10:52:06,41.984890,-88.080261,NaN,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day
1,A-167825,MapQuest,201.0,2,2016-12-09 09:47:36,2016-12-09 10:47:20,41.803619,-87.930847,NaN,NaN,...,False,False,False,False,False,False,Day,Day,Day,Day
2,A-167826,MapQuest,201.0,2,2016-12-09 10:29:10,2016-12-09 11:14:00,41.850239,-88.009613,NaN,NaN,...,False,False,False,False,False,False,Day,Day,Day,Day
3,A-167827,MapQuest,201.0,2,2016-12-09 10:29:10,2016-12-09 11:14:00,41.845898,-87.983032,NaN,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day
4,A-167828,MapQuest,201.0,2,2016-12-09 10:29:10,2016-12-09 11:14:00,41.846500,-87.963287,NaN,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168477,A-336302,MapQuest,201.0,2,2017-02-13 21:57:33,2017-02-13 22:27:03,38.351616,-123.060783,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
168478,A-336303,MapQuest,201.0,2,2017-02-13 21:58:17,2017-02-13 22:28:00,37.496815,-122.234467,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
168479,A-336304,MapQuest,201.0,2,2017-02-13 22:04:50,2017-02-13 22:34:28,39.112926,-121.082222,NaN,NaN,...,False,False,False,False,True,False,Night,Night,Night,Night
168480,A-336305,MapQuest,201.0,2,2017-02-13 22:12:44,2017-02-13 22:42:29,37.545795,-122.288956,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
168481,A-336306,MapQuest,203.0,2,2017-02-13 22:12:07,2017-02-13 22:41:47,37.509953,-122.251465,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night

# Getting top 5 rows of the dataframe

In [6]:
dask_df.head()

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,MapQuest,201.0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,MapQuest,201.0,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,MapQuest,201.0,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,MapQuest,201.0,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,MapQuest,201.0,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day

# Getting last 5 rows

In [7]:
dask_df.tail()

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
126531,A-3513776,Bing,NaN,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.00248,-117.37936,33.99888,-117.37094,...,False,False,False,False,False,False,Day,Day,Day,Day
126532,A-3513777,Bing,NaN,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.76696,-117.14806,32.76555,-117.15363,...,False,False,False,False,False,False,Day,Day,Day,Day
126533,A-3513778,Bing,NaN,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.77545,-117.84779,33.77740,-117.85727,...,False,False,False,False,False,False,Day,Day,Day,Day
126534,A-3513779,Bing,NaN,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.99246,-118.40302,33.98311,-118.39565,...,False,False,False,False,False,False,Day,Day,Day,Day
126535,A-3513780,Bing,NaN,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.13393,-117.23092,34.13736,-117.23934,...,False,False,False,False,False,False,Day,Day,Day,Day

# Checking dtypes

In [8]:
dask_df.dtypes

ID                        object
Source                    object
TMC                      float64
Severity                   int64
Start_Time                object
End_Time                  object
Start_Lat                float64
Start_Lng                float64
End_Lat                  float64
End_Lng                  float64
Distance(mi)             float64
Description               object
Number                   float64
Street                    object
Side                      object
City                      object
County                    object
State                     object
Zipcode                   object
Country                   object
Timezone                  object
Airport_Code              object
Weather_Timestamp         object
Temperature(F)           float64
Wind_Chill(F)            float64
Humidity(%)              float64
Pressure(in)             float64
Visibility(mi)           float64
Wind_Direction            object
Wind_Speed(mph)          float64
Precipitation(in)        float64
Weather_Condition         object
Amenity                     bool
Bump                        bool
Crossing                    bool
Give_Way                    bool
Junction                    bool
No_Exit                     bool
Railway                     bool
Roundabout                  bool
Station                     bool
Stop                        bool
Traffic_Calming             bool
Traffic_Signal              bool
Turning_Loop                bool
Sunrise_Sunset            object
Civil_Twilight            object
Nautical_Twilight         object
Astronomical_Twilight     object
dtype: object

# Getting five number summary with mean and count.

In [9]:
dask_df.describe().compute()

,TMC,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Number,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in)
count,2.478818e+06,3.513617e+06,3.513617e+06,3.513617e+06,1.034799e+06,1.034799e+06,3.513617e+06,1.250753e+06,3.447885e+06,1.645368e+06,3.443930e+06,3.457735e+06,3.437761e+06,3.059008e+06,1.487743e+06
mean,2.080226e+02,2.339929e+00,3.654195e+01,-9.579151e+01,3.755758e+01,-1.004560e+02,2.816167e-01,5.975383e+03,6.193512e+01,5.355730e+01,6.511427e+01,2.974463e+01,9.122644e+00,8.219025e+00,1.598256e-02
std,2.076627e+01,5.521935e-01,4.883520e+00,1.736877e+01,4.861215e+00,1.852879e+01,1.550134e+00,1.496624e+04,1.862106e+01,2.377334e+01,2.275558e+01,8.319758e-01,2.885879e+00,5.262847e+00,1.928262e-01
min,2.000000e+02,1.000000e+00,2.455527e+01,-1.246238e+02,2.457011e+01,-1.244978e+02,0.000000e+00,0.000000e+00,-8.900000e+01,-8.900000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.010000e+02,2.000000e+00,3.403389e+01,-9.855775e+01,3.403955e+01,-1.179203e+02,0.000000e+00,1.400500e+03,5.700000e+01,4.140000e+01,5.600000e+01,2.989000e+01,1.000000e+01,5.800000e+00,0.000000e+00
50%,2.010000e+02,2.000000e+00,3.889557e+01,-8.676523e+01,3.889513e+01,-9.156361e+01,0.000000e+00,4.429000e+03,7.000000e+01,6.400000e+01,7.500000e+01,3.001000e+01,1.000000e+01,8.100000e+00,0.000000e+00
75%,2.010000e+02,3.000000e+00,4.183397e+01,-7.556890e+01,4.183491e+01,-8.032533e+01,6.920000e-01,1.712550e+04,8.500000e+01,8.500000e+01,8.900000e+01,3.030000e+01,1.000000e+01,1.270000e+01,5.000000e-02
max,4.060000e+02,4.000000e+00,4.900220e+01,-6.711317e+01,4.907500e+01,-6.710924e+01,3.336300e+02,9.999997e+06,1.706000e+02,1.150000e+02,1.000000e+02,5.774000e+01,1.400000e+02,9.840000e+02,2.500000e+01

# Setting  ID column as a index

In [10]:
dask_df = dask_df.set_index('ID')
dask_df

Dask DataFrame Structure:
                Source      TMC Severity Start_Time End_Time Start_Lat Start_Lng  End_Lat  End_Lng Distance(mi) Description   Number  Street    Side    City  County   State Zipcode Country Timezone Airport_Code Weather_Timestamp Temperature(F) Wind_Chill(F) Humidity(%) Pressure(in) Visibility(mi) Wind_Direction Wind_Speed(mph) Precipitation(in) Weather_Condition Amenity  Bump Crossing Give_Way Junction No_Exit Railway Roundabout Station  Stop Traffic_Calming Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight Nautical_Twilight Astronomical_Twilight
npartitions=21
A-1             object  float64    int64     object   object   float64   float64  float64  float64      float64      object  float64  object  object  object  object  object  object  object   object       object            object        float64       float64     float64      float64        float64         object         float64           float64            object    bool  bool     bool     bool     bool    bool    bool       bool    bool  bool            bool           bool         bool         object         object            object                object
A-1146561          ...      ...      ...        ...      ...       ...       ...      ...      ...          ...         ...      ...     ...     ...     ...     ...     ...     ...     ...      ...          ...               ...            ...           ...         ...          ...            ...            ...             ...               ...               ...     ...   ...      ...      ...      ...     ...     ...        ...     ...   ...             ...            ...          ...            ...            ...               ...                   ...
...                ...      ...      ...        ...      ...       ...       ...      ...      ...          ...         ...      ...     ...     ...     ...     ...     ...     ...     ...      ...          ...               ...            ...           ...         ...          ...            ...            ...             ...               ...               ...     ...   ...      ...      ...      ...     ...     ...        ...     ...   ...             ...            ...          ...            ...            ...               ...                   ...
A-841734           ...      ...      ...        ...      ...       ...       ...      ...      ...          ...         ...      ...     ...     ...     ...     ...     ...     ...     ...      ...          ...               ...            ...           ...         ...          ...            ...            ...             ...               ...               ...     ...   ...      ...      ...      ...     ...     ...        ...     ...   ...             ...            ...          ...            ...            ...               ...                   ...
A-999999           ...      ...      ...        ...      ...       ...       ...      ...      ...          ...         ...      ...     ...     ...     ...     ...     ...     ...     ...      ...          ...               ...            ...           ...         ...          ...            ...            ...             ...               ...               ...     ...   ...      ...      ...      ...     ...     ...        ...     ...   ...             ...            ...          ...            ...            ...               ...                   ...
Dask Name: sort_index, 213 tasks

# Appending new columns

**Severity shows the impact on traffic duration.So lets find append a new column which gives True if traffic duration is too long.**

In [11]:
dask_df['long_delay'] = dask_df['Severity']==4
dask_df.head()

,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,long_delay
ID,,,,,,,,,,,,,,,,,,,,,
A-1,MapQuest,201.0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,Night,Night,Night,Night,False
A-10,MapQuest,201.0,3,2016-02-08 08:10:04,2016-02-08 08:40:04,40.100590,-82.925194,NaN,NaN,0.01,...,False,False,False,False,False,Day,Day,Day,Day,False
A-100,MapQuest,201.0,2,2016-02-11 08:13:24,2016-02-11 08:43:24,39.749916,-84.139359,NaN,NaN,0.01,...,False,False,False,False,False,Day,Day,Day,Day,False
A-1000,MapQuest,201.0,2,2016-06-23 10:31:12,2016-06-23 11:01:12,38.653061,-121.070541,NaN,NaN,0.00,...,False,False,False,False,False,Day,Day,Day,Day,False
A-10000,MapQuest,201.0,3,2017-01-06 16:22:04,2017-01-06 16:51:29,38.574406,-121.577354,NaN,NaN,0.01,...,False,False,False,False,False,Day,Day,Day,Day,False

# Changing datatypes of columns

In [12]:
dask_df['long_delay'].dtype                                  # output: bool
dask_df['long_delay'] = dask_df['long_delay'].astype('int')
dask_df['long_delay'].dtype                                  # output: int64

dtype('int64')

# Getting unique element

In [13]:
dask_df['Severity'].unique().compute()

'''
Output: 
0 3
1 2
2 4
3 1
'''

'\nOutput: \n0 3\n1 2\n2 4\n3 1\n'

# Count of each unique element

In [14]:
dask_df['Severity'].value_counts().compute()

'''
Output: 
2   2373210
3   998913
4   112320
1   29174
'''

'\nOutput: \n2   2373210\n3   998913\n4   112320\n1   29174\n'

# Accessing the data of data frame

###  1.  Access particular row

In [15]:
dask_df.loc['A-3'].compute()

,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,long_delay
ID,,,,,,,,,,,,,,,,,,,,,
A-3,MapQuest,201.0,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,0.01,...,False,False,False,True,False,Night,Night,Day,Day,0

###  2.  Access particular column

In [16]:
dask_df.loc[:,'City'].compute()

ID
A-1                  Dayton
A-10            Westerville
A-100                Dayton
A-1000      El Dorado Hills
A-10000     West Sacramento
                 ...
A-999995            Antioch
A-999996          Nashville
A-999997       Whites Creek
A-999998          Nashville
A-999999            Madison
Name: City, Length: 3513617, dtype: object

###   3.  Access particular row and column

In [17]:
dask_df.loc['A-100','State'].compute()

'''
Output:
ID
A-100   OH
Name:  State, dtype:  object
'''

'\nOutput:\nID\nA-100   OH\nName:  State, dtype:  object\n'

### 4. Accessing a range of rows

In [18]:
dask_df.loc['A-5':'A-9']

Dask DataFrame Structure:
               Source      TMC Severity Start_Time End_Time Start_Lat Start_Lng  End_Lat  End_Lng Distance(mi) Description   Number  Street    Side    City  County   State Zipcode Country Timezone Airport_Code Weather_Timestamp Temperature(F) Wind_Chill(F) Humidity(%) Pressure(in) Visibility(mi) Wind_Direction Wind_Speed(mph) Precipitation(in) Weather_Condition Amenity  Bump Crossing Give_Way Junction No_Exit Railway Roundabout Station  Stop Traffic_Calming Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight Nautical_Twilight Astronomical_Twilight long_delay
npartitions=4
A-5            object  float64    int64     object   object   float64   float64  float64  float64      float64      object  float64  object  object  object  object  object  object  object   object       object            object        float64       float64     float64      float64        float64         object         float64           float64            object    bool  bool     bool     bool     bool    bool    bool       bool    bool  bool            bool           bool         bool         object         object            object                object      int64
A-525713          ...      ...      ...        ...      ...       ...       ...      ...      ...          ...         ...      ...     ...     ...     ...     ...     ...     ...     ...      ...          ...               ...            ...           ...         ...          ...            ...            ...             ...               ...               ...     ...   ...      ...      ...      ...     ...     ...        ...     ...   ...             ...            ...          ...            ...            ...               ...                   ...        ...
A-690399          ...      ...      ...        ...      ...       ...       ...      ...      ...          ...         ...      ...     ...     ...     ...     ...     ...     ...     ...      ...          ...               ...            ...           ...         ...          ...            ...            ...             ...               ...               ...     ...   ...      ...      ...      ...     ...     ...        ...     ...   ...             ...            ...          ...            ...            ...               ...                   ...        ...
A-841734          ...      ...      ...        ...      ...       ...       ...      ...      ...          ...         ...      ...     ...     ...     ...     ...     ...     ...     ...      ...          ...               ...            ...           ...         ...          ...            ...            ...             ...               ...               ...     ...   ...      ...      ...      ...     ...     ...        ...     ...   ...             ...            ...          ...            ...            ...               ...                   ...        ...
A-9               ...      ...      ...        ...      ...       ...       ...      ...      ...          ...         ...      ...     ...     ...     ...     ...     ...     ...     ...      ...          ...               ...            ...           ...         ...          ...            ...            ...             ...               ...               ...     ...   ...      ...      ...      ...     ...     ...        ...     ...   ...             ...            ...          ...            ...            ...               ...                   ...        ...
Dask Name: loc, 343 tasks

# Condition search

In [19]:
dask_df[dask_df['Start_Lat']== 39.865147].compute()

,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,long_delay
ID,,,,,,,,,,,,,,,,,,,,,
A-1,MapQuest,201.0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,0.01,...,False,False,False,False,False,Night,Night,Night,Night,0
A-223980,MapQuest,201.0,3,2016-11-01 14:38:32,2016-11-01 15:50:00,39.865147,-84.188736,NaN,NaN,0.01,...,False,False,False,False,False,Day,Day,Day,Day,0

# Multiple Condiational Search

In [20]:
dask_df[da.logical_and(dask_df['Start_Lng']==-86.779770,dask_df['Start_Lat']== 36.194839)].compute()

,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,long_delay
ID,,,,,,,,,,,,,,,,,,,,,
A-1000001,MapQuest,202.0,2,2019-08-26 08:23:20,2019-08-26 09:23:09,36.194839,-86.77977,NaN,NaN,0.0,...,False,False,False,False,False,Day,Day,Day,Day,0
A-583291,MapQuest,201.0,2,2020-03-06 07:46:04,2020-03-06 08:45:45,36.194839,-86.77977,NaN,NaN,0.0,...,False,False,False,False,False,Day,Day,Day,Day,0

# Getting the Number of Null values of each columns

In [21]:
dask_df.isna().sum(axis=0).compute()

Source                         0
TMC                      1034799
Severity                       0
Start_Time                     0
End_Time                       0
Start_Lat                      0
Start_Lng                      0
End_Lat                  2478818
End_Lng                  2478818
Distance(mi)                   0
Description                    1
Number                   2262864
Street                         0
Side                           0
City                         112
County                         0
State                          0
Zipcode                     1069
Country                        0
Timezone                    3880
Airport_Code                6758
Weather_Timestamp          43323
Temperature(F)             65732
Wind_Chill(F)            1868249
Humidity(%)                69687
Pressure(in)               55882
Visibility(mi)             75856
Wind_Direction             58874
Wind_Speed(mph)           454609
Precipitation(in)        2025874
Weather_Condition          76138
Amenity                        0
Bump                           0
Crossing                       0
Give_Way                       0
Junction                       0
No_Exit                        0
Railway                        0
Roundabout                     0
Station                        0
Stop                           0
Traffic_Calming                0
Traffic_Signal                 0
Turning_Loop                   0
Sunrise_Sunset               115
Civil_Twilight               115
Nautical_Twilight            115
Astronomical_Twilight        115
long_delay                     0
dtype: int64

# Filling Null values

In [22]:
dask_df['Wind_Speed(mph)'].isnull().sum().compute()  # output 454609

454609

In [23]:
dask_df['Wind_Speed(mph)'] = dask_df['Wind_Speed(mph)'].fillna(10)

In [24]:
dask_df['Wind_Speed(mph)'].isnull().sum().compute()  # output 0

0

# Drop rows with Null value

In [25]:
dask_df = dask_df.dropna(subset=['Zipcode'])

# Dropping columns

In [26]:
print(any(dask_df.columns=='long_delay'))       # output True
dask_df = dask_df.drop('long_delay',axis=1)
print(any(dask_df.columns=='long_delay'))       # output False

True
False

# Groupby method

In [27]:
byState = dask_df.groupby('State')

In [28]:
byState['Temperature(F)'].mean().compute()

State
AL    66.919484
AR    62.531729
AZ    75.710751
CA    64.972313
CO    48.828709
CT    53.648502
DC    59.778882
DE    57.023645
FL    75.368729
GA    65.343688
IA    48.044378
ID    50.248567
IL    52.047952
IN    54.501243
KS    56.756222
KY    58.459441
LA    71.729769
MA    51.345934
MD    57.477447
ME    50.294858
MI    50.381913
MN    39.768319
MO    57.076073
MS    66.542299
NC    63.364943
ND    42.483721
NE    54.341196
NH    47.898077
NJ    55.858550
NM    59.618050
NV    59.245684
NY    53.749160
OH    53.421258
OK    63.663190
OR    53.037263
PA    55.051521
RI    54.062694
SC    65.409989
TN    62.085779
TX    70.887868
UT    51.418052
VA    59.774498
VT    44.069154
WA    54.322343
WI    46.054374
WV    56.619872
WY    36.949900
SD    41.633333
MT    32.237769
Name: Temperature(F), dtype: float64